version: "3.8"
services:
  db:
    container_name: byos-db
    restart: always
    image: byos-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432
  graphql:
    container_name: byos-app
    restart: always
    image: byos-app
    build:
      context: ./
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 8080:8080
networks:
  network:

volumes:
  db: