version: "3.8"
services:
  db:
    container_name: byos-db
    restart: always
    image: postgres:14.0-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    ports:
      - 5433:5432
  graphql:
    container_name: byos-app
    restart: always
    image: byos-app
    build:
      context: ./
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  db: